### ISSUE TITLE
Enhancement: Add 'scrollTo' method to scroll to specific item 

### ISSUE THREAD

**Issue by Tmodurr** [albertodeago/vue-virtualized-list#11]
Support scrollTo behavior based on item index

**Comment by albertodeago** [comment]
Hi @Tmodurr, I'll look into that feature, thanks for the suggestion!

**Comment by mmouterde** [comment]
Setting `firstToRender` to the item index you want does not fit your needs ?

**Comment by Tmodurr** [comment]
@mmouterde you mentioned "Setting firstToRender to the item index you want does not fit your needs ?" Did you remove this comment? just curious before I look into this if it's still viable

**Comment by Tmodurr** [comment]
@albertodeago just curious if you've been able to look into this? Thank you for this library in any case

**Comment by mmouterde** [comment]
@Tmodurr I realized my suggestion is not an options as firstToRender is not exposed yet.

**Comment by albertodeago** [comment]
@Tmodurr Looking at this today

**Comment by mmouterde** [comment]
@albertodeago I've just started a branch to working on a scrollTo function.
https://github.com/mmouterde/vue-virtualized-list/tree/11_scrollToFn

**Comment by albertodeago** [comment]
@mmouterde man you're a god, that's pretty much the same I was going to do... If you prefer I'll wait your PR then, let me know
